; СЕБАСТЬЯН — стендовый тест, СО-ПРОЦЕССОР (обычная ESP32, CH340)
; v5: Bluetooth-колонка (A2DP) -> PCM5102A -> AUX, радио 433, тестовая мелодия,
; ARGB, 3 сенсора, кнопка мика, замер батареи, UART к S3.

[env:esp32]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv   ; Bluetooth занимает много места — большой раздел под прошивку
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    sui77/rc-switch@^2.6.4
    https://github.com/pschatzmann/ESP32-A2DP/archive/refs/tags/v.1.7.5.zip