; СЕБАСТЬЯН — стендовый тест, СО-ПРОЦЕССОР (обычная ESP32, CH340)
; v2: PCM5102A (AUX) бип, ARGB, 3 сенсора, кнопка мика,
; замер батареи, UART к S3.

[env:esp32]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0